/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: filehead.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "filehead.pb-c.h"
void   file_info__init
                     (FileInfo         *message)
{
  static FileInfo init_value = FILE_INFO__INIT;
  *message = init_value;
}
size_t file_info__get_packed_size
                     (const FileInfo *message)
{
  assert(message->base.descriptor == &file_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file_info__pack
                     (const FileInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &file_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file_info__pack_to_buffer
                     (const FileInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &file_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FileInfo *
       file_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FileInfo *)
     protobuf_c_message_unpack (&file_info__descriptor,
                                allocator, len, data);
}
void   file_info__free_unpacked
                     (FileInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &file_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor file_info__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FileInfo, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(FileInfo, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(FileInfo, info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file_info__field_indices_by_name[] = {
  2,   /* field[2] = info */
  0,   /* field[0] = name */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange file_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor file_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FileInfo",
  "FileInfo",
  "FileInfo",
  "",
  sizeof(FileInfo),
  3,
  file_info__field_descriptors,
  file_info__field_indices_by_name,
  1,  file_info__number_ranges,
  (ProtobufCMessageInit) file_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
